# 端口
server:
  port: 7000

# 关闭模板引擎缓存
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
  servlet:
    #上传文件大小限制
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/r_pan?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # mysql8.0以前使用com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    # TODO 修改用户名和密码
    username: username
    password: password
    platform: mysql
    # 通过这句配置将druid连接池引入到我们的配置中，spring会尽可能判断类型是什么，然后根据情况去匹配驱动类。
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小
      initial-size: 5
      # 最小
      min-idle: 5
      # 最大
      max-active: 100
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validationQuery: select 'x'
      # 当连接空闲时，是否执行连接测试
      test-while-idle: true
      # 当从连接池借用连接时，是否测试该连接
      test-on-borrow: false
      # 在连接归还到连接池时是否测试该连接
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: config,wall,stat
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=false
      # 合并多个DruidDataSource的监控数据
      # use-global-data-source-stat: true
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        # 是否启用StatFilter默认值true
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        # 是否启用StatViewServlet默认值true
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin

# mybatis
mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: com.rubin.rpan.entity

# 文件系统根目录
file:
  root:
    # TODO path为文件上传的实际文件地址 生产和本地环境都要保证此文件夹有读写权限
    path: path
    # TODO zip-path为临时压缩文件的存放地址 生产和本地环境都要保证此文件夹有读写权限
    zip-path: zip-path
    # TODO nginx-path为nginx配置好静态资源转发之后的前缀
    nginx-path: nginx-path

# 打开监控器的所有节点
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
